export const BUSINESS_NATURE_CATEGORIES: string[] = [
  'Cameras and Accessories',
  'Fitness',
  'Transport',
  'Professional Services',
  'Personal Care',
  'Food and Food Products',
  'Media and Advertising',
  'Gems and Jewellery',
  'Metals',
  'Chemicals and Chemical Products',
  'Plastic and Rubber',
  'Pet Products',
  'Industrial Equipments',
  'Pharmacy',
  'Customer Service',
  'Professionals',
  'Tourism and Hospitality',
  'Stationery',
  'Sports Items',
];
